spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
  flyway:
    enabled: true
    locations: [ "classpath:/db/migration" ]

dify:
  api:
    base-url: https://api.dify.ai/v1
    key: 填写你的dify api key